menu:
- {name: 'projects', url: '/projects'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

projects:
- {name: 'Human Mobility within Urban Geography', url: 'mobility'}
- {name: 'Sustainable Urban system', url: 'sustainable'}
- {name: 'Technological Innovation', url: 'innovation'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {text: 'Google scholar', icon: 'ai ai-google-scholar-square', link: 'https://scholar.google.com/citations?user=ugw2C8UAAAAJ'}
- {text: 'Github', icon: 'fab fa-github', link: 'https://github.com/pothyd'}
- {text: 'LinkedIn', icon: 'fab fa-linkedin', link: 'https://linkedin.com/in/kwon-oh-hyun-907b22134/'}

contacts:
- {name: 'Oh-Hyun Kwon', title: 'Senior researcher', department: 'Institute for Future Strategy', institution: 'Seoul National University', institution_address: '1 Gwanak-ro, Seoul, Republic of Korea', email: 'ohhyun@snu.ac.kr'}
